sudo: required
services:
  - docker
language: bash
env:
  matrix:
    - MAKE_TARGET=armhf-raspbian
script:
  - make shellcheck
  - HYPRIOT_OS_VERSION=${TRAVIS_TAG} make ${MAKE_TARGET}
branches:
  only:
    - master
    - /^v\d.*$/
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - rootfs-${MAKE_TARGET}-${TRAVIS_TAG}.tar.gz
    - rootfs-${MAKE_TARGET}-${TRAVIS_TAG}.tar.gz.sha256
  on:
    tags: true
    repo: arnobroekhof/os-rootfs
  api_key:
    secure: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtjtduozpiRonyRHxG8+h\nNd4ZEcMkesxoapwap0DPDIivoaly1zAJXPcTSqjHfBC1Bp4c+P1luAm+7hbBZIDy\nA41jtVWYosGCQ4VYNcfsoxGJvBanFXDmlgkRpsX4ZWIyRZXW6RtQw7AjNp3qaiNI\nNB6l04qMoROLO4RekYGDlI2YHE8/iAvcjnabudd+FFcfXncyV6G/Iix16YqNFTo1\nqDBTjAWGjF4aMiwCsOvdd7VHEfre8PHDEV2MgEgrA+SDPYl7OUxJL8DqjMYN7iIx\nQ/mjJgEp0Pmmh1nL/s34uc9c94BAG+hjvi27/P5lenl9MLKraZvBH3/cqwbFBI5+\nx9LubziEE+X2KWUAsWh0t95f7AkkvvKsIpURNs6gVxHbqdrY5KWSys+pmyRvPFXY\nyg6QMq8yuK0j9B4MGiZbn6XYKhpsfoprwGJEYhmPJV0CkM7iFi4Ya/aLO18cl398\nJUkOUo/+6aRoZgacGpa6SlQP2DX9k4XGQfrtgnrhT563mx08r55aRRH6bzN0nRfC\njbqaJMmqTsSv8KA/cWvsczOA0xubA0oraCBEvY1hoqV0g20fFBAKoiemX0N6VEqV\nnZnWbyVdvz12JtxTb2sm7unJdVvw3e6oAGPKkezrURnu3RsGDx4R9hpChJ0OL4Tu\nE/t4qDQeMtg1ioxgi81LDocCAwEAAQ==
